# 工作流名称，可自定义
name: test
# 触发条件
on:
  push:
    branches: [ master ]
# 任务    
jobs:
  deploy:
  	# 使用ubuntu系统镜像运行自动化脚本
    runs-on: ubuntu-latest
    # 自动化步骤
    steps:
      # 第一步，下载代码仓库
      - uses: actions/checkout@v2
      # 第二步，推文件到服务器，使用rsync
      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_KEY }}
          ARGS: -avz --no-owner --no-group --no-perms --progress --exclude='.*' --exclude='/vendor' --exclude='storage/logs/' --delete
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          # 要推送的文件夹，路径相对于代码仓库的根目录
          FOLDER: ./
          SERVER_IP: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_DESTINATION: /tmp/laravel-test
      # 第三步，登录服务器，执行安装依赖等操作   
      - name: Execute Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd /tmp/laravel-test
            chmod -R 777 storage/
            composer install

